<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit67c38f125e4686a9e2bb3477b359708e
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit67c38f125e4686a9e2bb3477b359708e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit67c38f125e4686a9e2bb3477b359708e::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
